/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AboutIndexRouteImport } from './routes/about.index'
import { Route as AboutHistoryRouteImport } from './routes/about.history'
import { Route as AboutLocationRouteImport } from './routes/about.location'
import { Route as AboutPressRouteImport } from './routes/about.press'
import { Route as AboutVisionRouteImport } from './routes/about.vision'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogIdRouteImport } from './routes/blog.$id'
import { Route as BusinessIndexRouteImport } from './routes/business.index'
import { Route as BusinessAiSolutionsRouteImport } from './routes/business.ai-solutions'
import { Route as BusinessDataAnalysisRouteImport } from './routes/business.data-analysis'
import { Route as BusinessEducationRouteImport } from './routes/business.education'
import { Route as BusinessPlatformRouteImport } from './routes/business.platform'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio.index'
import { Route as PortfolioIdRouteImport } from './routes/portfolio.$id'
import { Route as SupportIndexRouteImport } from './routes/support.index'
import { Route as SupportContactRouteImport } from './routes/support.contact'
import { Route as SupportFaqRouteImport } from './routes/support.faq'
import { Route as SupportNoticesRouteImport } from './routes/support.notices'
import { Route as AdminBlogIndexRouteImport } from './routes/admin.blog.index'
import { Route as AdminBlogIdRouteImport } from './routes/admin.blog.$id'
import { Route as AdminBlogNewRouteImport } from './routes/admin.blog.new'
import { Route as AdminInquiriesIndexRouteImport } from './routes/admin.inquiries.index'
import { Route as AdminInquiriesIdRouteImport } from './routes/admin.inquiries.$id'
import { Route as AdminNoticesIndexRouteImport } from './routes/admin.notices.index'
import { Route as AdminNoticesIdRouteImport } from './routes/admin.notices.$id'
import { Route as AdminNoticesNewRouteImport } from './routes/admin.notices.new'
import { Route as AdminPortfolioIndexRouteImport } from './routes/admin.portfolio.index'
import { Route as AdminPortfolioIdRouteImport } from './routes/admin.portfolio.$id'
import { Route as AdminPortfolioNewRouteImport } from './routes/admin.portfolio.new'
import { Route as AdminPressIndexRouteImport } from './routes/admin.press.index'
import { Route as AdminPressIdRouteImport } from './routes/admin.press.$id'
import { Route as AdminPressNewRouteImport } from './routes/admin.press.new'
import { Route as SupportNoticesIndexRouteImport } from './routes/support.notices.index'
import { Route as SupportNoticesIdRouteImport } from './routes/support.notices.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutHistoryRoute = AboutHistoryRouteImport.update({
  id: '/about/history',
  path: '/about/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutLocationRoute = AboutLocationRouteImport.update({
  id: '/about/location',
  path: '/about/location',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutPressRoute = AboutPressRouteImport.update({
  id: '/about/press',
  path: '/about/press',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutVisionRoute = AboutVisionRouteImport.update({
  id: '/about/vision',
  path: '/about/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogIdRoute = BlogIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BlogRoute,
} as any)
const BusinessIndexRoute = BusinessIndexRouteImport.update({
  id: '/business/',
  path: '/business/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessAiSolutionsRoute = BusinessAiSolutionsRouteImport.update({
  id: '/business/ai-solutions',
  path: '/business/ai-solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessDataAnalysisRoute = BusinessDataAnalysisRouteImport.update({
  id: '/business/data-analysis',
  path: '/business/data-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessEducationRoute = BusinessEducationRouteImport.update({
  id: '/business/education',
  path: '/business/education',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessPlatformRoute = BusinessPlatformRouteImport.update({
  id: '/business/platform',
  path: '/business/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortfolioRoute,
} as any)
const PortfolioIdRoute = PortfolioIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PortfolioRoute,
} as any)
const SupportIndexRoute = SupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportContactRoute = SupportContactRouteImport.update({
  id: '/support/contact',
  path: '/support/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportFaqRoute = SupportFaqRouteImport.update({
  id: '/support/faq',
  path: '/support/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportNoticesRoute = SupportNoticesRouteImport.update({
  id: '/support/notices',
  path: '/support/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogIdRoute = AdminBlogIdRouteImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogNewRoute = AdminBlogNewRouteImport.update({
  id: '/blog/new',
  path: '/blog/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInquiriesIndexRoute = AdminInquiriesIndexRouteImport.update({
  id: '/inquiries/',
  path: '/inquiries/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInquiriesIdRoute = AdminInquiriesIdRouteImport.update({
  id: '/inquiries/$id',
  path: '/inquiries/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNoticesIndexRoute = AdminNoticesIndexRouteImport.update({
  id: '/notices/',
  path: '/notices/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNoticesIdRoute = AdminNoticesIdRouteImport.update({
  id: '/notices/$id',
  path: '/notices/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNoticesNewRoute = AdminNoticesNewRouteImport.update({
  id: '/notices/new',
  path: '/notices/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPortfolioIndexRoute = AdminPortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPortfolioIdRoute = AdminPortfolioIdRouteImport.update({
  id: '/portfolio/$id',
  path: '/portfolio/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPortfolioNewRoute = AdminPortfolioNewRouteImport.update({
  id: '/portfolio/new',
  path: '/portfolio/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPressIndexRoute = AdminPressIndexRouteImport.update({
  id: '/press/',
  path: '/press/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPressIdRoute = AdminPressIdRouteImport.update({
  id: '/press/$id',
  path: '/press/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPressNewRoute = AdminPressNewRouteImport.update({
  id: '/press/new',
  path: '/press/new',
  getParentRoute: () => AdminRoute,
} as any)
const SupportNoticesIndexRoute = SupportNoticesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SupportNoticesRoute,
} as any)
const SupportNoticesIdRoute = SupportNoticesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SupportNoticesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/portfolio': typeof PortfolioRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/about/history': typeof AboutHistoryRoute
  '/about/location': typeof AboutLocationRoute
  '/about/press': typeof AboutPressRoute
  '/about/vision': typeof AboutVisionRoute
  '/blog/$id': typeof BlogIdRoute
  '/business/ai-solutions': typeof BusinessAiSolutionsRoute
  '/business/data-analysis': typeof BusinessDataAnalysisRoute
  '/business/education': typeof BusinessEducationRoute
  '/business/platform': typeof BusinessPlatformRoute
  '/portfolio/$id': typeof PortfolioIdRoute
  '/support/contact': typeof SupportContactRoute
  '/support/faq': typeof SupportFaqRoute
  '/support/notices': typeof SupportNoticesRouteWithChildren
  '/about/': typeof AboutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/business/': typeof BusinessIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/support/': typeof SupportIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/inquiries/$id': typeof AdminInquiriesIdRoute
  '/admin/notices/$id': typeof AdminNoticesIdRoute
  '/admin/notices/new': typeof AdminNoticesNewRoute
  '/admin/portfolio/$id': typeof AdminPortfolioIdRoute
  '/admin/portfolio/new': typeof AdminPortfolioNewRoute
  '/admin/press/$id': typeof AdminPressIdRoute
  '/admin/press/new': typeof AdminPressNewRoute
  '/support/notices/$id': typeof SupportNoticesIdRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/inquiries/': typeof AdminInquiriesIndexRoute
  '/admin/notices/': typeof AdminNoticesIndexRoute
  '/admin/portfolio/': typeof AdminPortfolioIndexRoute
  '/admin/press/': typeof AdminPressIndexRoute
  '/support/notices/': typeof SupportNoticesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/about/history': typeof AboutHistoryRoute
  '/about/location': typeof AboutLocationRoute
  '/about/press': typeof AboutPressRoute
  '/about/vision': typeof AboutVisionRoute
  '/blog/$id': typeof BlogIdRoute
  '/business/ai-solutions': typeof BusinessAiSolutionsRoute
  '/business/data-analysis': typeof BusinessDataAnalysisRoute
  '/business/education': typeof BusinessEducationRoute
  '/business/platform': typeof BusinessPlatformRoute
  '/portfolio/$id': typeof PortfolioIdRoute
  '/support/contact': typeof SupportContactRoute
  '/support/faq': typeof SupportFaqRoute
  '/about': typeof AboutIndexRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/business': typeof BusinessIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/support': typeof SupportIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/inquiries/$id': typeof AdminInquiriesIdRoute
  '/admin/notices/$id': typeof AdminNoticesIdRoute
  '/admin/notices/new': typeof AdminNoticesNewRoute
  '/admin/portfolio/$id': typeof AdminPortfolioIdRoute
  '/admin/portfolio/new': typeof AdminPortfolioNewRoute
  '/admin/press/$id': typeof AdminPressIdRoute
  '/admin/press/new': typeof AdminPressNewRoute
  '/support/notices/$id': typeof SupportNoticesIdRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/inquiries': typeof AdminInquiriesIndexRoute
  '/admin/notices': typeof AdminNoticesIndexRoute
  '/admin/portfolio': typeof AdminPortfolioIndexRoute
  '/admin/press': typeof AdminPressIndexRoute
  '/support/notices': typeof SupportNoticesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/portfolio': typeof PortfolioRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/about/history': typeof AboutHistoryRoute
  '/about/location': typeof AboutLocationRoute
  '/about/press': typeof AboutPressRoute
  '/about/vision': typeof AboutVisionRoute
  '/blog/$id': typeof BlogIdRoute
  '/business/ai-solutions': typeof BusinessAiSolutionsRoute
  '/business/data-analysis': typeof BusinessDataAnalysisRoute
  '/business/education': typeof BusinessEducationRoute
  '/business/platform': typeof BusinessPlatformRoute
  '/portfolio/$id': typeof PortfolioIdRoute
  '/support/contact': typeof SupportContactRoute
  '/support/faq': typeof SupportFaqRoute
  '/support/notices': typeof SupportNoticesRouteWithChildren
  '/about/': typeof AboutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/business/': typeof BusinessIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/support/': typeof SupportIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/inquiries/$id': typeof AdminInquiriesIdRoute
  '/admin/notices/$id': typeof AdminNoticesIdRoute
  '/admin/notices/new': typeof AdminNoticesNewRoute
  '/admin/portfolio/$id': typeof AdminPortfolioIdRoute
  '/admin/portfolio/new': typeof AdminPortfolioNewRoute
  '/admin/press/$id': typeof AdminPressIdRoute
  '/admin/press/new': typeof AdminPressNewRoute
  '/support/notices/$id': typeof SupportNoticesIdRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/inquiries/': typeof AdminInquiriesIndexRoute
  '/admin/notices/': typeof AdminNoticesIndexRoute
  '/admin/portfolio/': typeof AdminPortfolioIndexRoute
  '/admin/press/': typeof AdminPressIndexRoute
  '/support/notices/': typeof SupportNoticesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/portfolio'
    | '/privacy'
    | '/terms'
    | '/about/history'
    | '/about/location'
    | '/about/press'
    | '/about/vision'
    | '/blog/$id'
    | '/business/ai-solutions'
    | '/business/data-analysis'
    | '/business/education'
    | '/business/platform'
    | '/portfolio/$id'
    | '/support/contact'
    | '/support/faq'
    | '/support/notices'
    | '/about/'
    | '/admin/'
    | '/blog/'
    | '/business/'
    | '/portfolio/'
    | '/support/'
    | '/admin/blog/$id'
    | '/admin/blog/new'
    | '/admin/inquiries/$id'
    | '/admin/notices/$id'
    | '/admin/notices/new'
    | '/admin/portfolio/$id'
    | '/admin/portfolio/new'
    | '/admin/press/$id'
    | '/admin/press/new'
    | '/support/notices/$id'
    | '/admin/blog/'
    | '/admin/inquiries/'
    | '/admin/notices/'
    | '/admin/portfolio/'
    | '/admin/press/'
    | '/support/notices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacy'
    | '/terms'
    | '/about/history'
    | '/about/location'
    | '/about/press'
    | '/about/vision'
    | '/blog/$id'
    | '/business/ai-solutions'
    | '/business/data-analysis'
    | '/business/education'
    | '/business/platform'
    | '/portfolio/$id'
    | '/support/contact'
    | '/support/faq'
    | '/about'
    | '/admin'
    | '/blog'
    | '/business'
    | '/portfolio'
    | '/support'
    | '/admin/blog/$id'
    | '/admin/blog/new'
    | '/admin/inquiries/$id'
    | '/admin/notices/$id'
    | '/admin/notices/new'
    | '/admin/portfolio/$id'
    | '/admin/portfolio/new'
    | '/admin/press/$id'
    | '/admin/press/new'
    | '/support/notices/$id'
    | '/admin/blog'
    | '/admin/inquiries'
    | '/admin/notices'
    | '/admin/portfolio'
    | '/admin/press'
    | '/support/notices'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/portfolio'
    | '/privacy'
    | '/terms'
    | '/about/history'
    | '/about/location'
    | '/about/press'
    | '/about/vision'
    | '/blog/$id'
    | '/business/ai-solutions'
    | '/business/data-analysis'
    | '/business/education'
    | '/business/platform'
    | '/portfolio/$id'
    | '/support/contact'
    | '/support/faq'
    | '/support/notices'
    | '/about/'
    | '/admin/'
    | '/blog/'
    | '/business/'
    | '/portfolio/'
    | '/support/'
    | '/admin/blog/$id'
    | '/admin/blog/new'
    | '/admin/inquiries/$id'
    | '/admin/notices/$id'
    | '/admin/notices/new'
    | '/admin/portfolio/$id'
    | '/admin/portfolio/new'
    | '/admin/press/$id'
    | '/admin/press/new'
    | '/support/notices/$id'
    | '/admin/blog/'
    | '/admin/inquiries/'
    | '/admin/notices/'
    | '/admin/portfolio/'
    | '/admin/press/'
    | '/support/notices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  PortfolioRoute: typeof PortfolioRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AboutHistoryRoute: typeof AboutHistoryRoute
  AboutLocationRoute: typeof AboutLocationRoute
  AboutPressRoute: typeof AboutPressRoute
  AboutVisionRoute: typeof AboutVisionRoute
  BusinessAiSolutionsRoute: typeof BusinessAiSolutionsRoute
  BusinessDataAnalysisRoute: typeof BusinessDataAnalysisRoute
  BusinessEducationRoute: typeof BusinessEducationRoute
  BusinessPlatformRoute: typeof BusinessPlatformRoute
  SupportContactRoute: typeof SupportContactRoute
  SupportFaqRoute: typeof SupportFaqRoute
  SupportNoticesRoute: typeof SupportNoticesRouteWithChildren
  AboutIndexRoute: typeof AboutIndexRoute
  BusinessIndexRoute: typeof BusinessIndexRoute
  SupportIndexRoute: typeof SupportIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/history': {
      id: '/about/history'
      path: '/about/history'
      fullPath: '/about/history'
      preLoaderRoute: typeof AboutHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/location': {
      id: '/about/location'
      path: '/about/location'
      fullPath: '/about/location'
      preLoaderRoute: typeof AboutLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/press': {
      id: '/about/press'
      path: '/about/press'
      fullPath: '/about/press'
      preLoaderRoute: typeof AboutPressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/vision': {
      id: '/about/vision'
      path: '/about/vision'
      fullPath: '/about/vision'
      preLoaderRoute: typeof AboutVisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$id': {
      id: '/blog/$id'
      path: '/$id'
      fullPath: '/blog/$id'
      preLoaderRoute: typeof BlogIdRouteImport
      parentRoute: typeof BlogRoute
    }
    '/business/': {
      id: '/business/'
      path: '/business'
      fullPath: '/business/'
      preLoaderRoute: typeof BusinessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/ai-solutions': {
      id: '/business/ai-solutions'
      path: '/business/ai-solutions'
      fullPath: '/business/ai-solutions'
      preLoaderRoute: typeof BusinessAiSolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/data-analysis': {
      id: '/business/data-analysis'
      path: '/business/data-analysis'
      fullPath: '/business/data-analysis'
      preLoaderRoute: typeof BusinessDataAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/education': {
      id: '/business/education'
      path: '/business/education'
      fullPath: '/business/education'
      preLoaderRoute: typeof BusinessEducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/platform': {
      id: '/business/platform'
      path: '/business/platform'
      fullPath: '/business/platform'
      preLoaderRoute: typeof BusinessPlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/portfolio/$id': {
      id: '/portfolio/$id'
      path: '/$id'
      fullPath: '/portfolio/$id'
      preLoaderRoute: typeof PortfolioIdRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/support/': {
      id: '/support/'
      path: '/support'
      fullPath: '/support/'
      preLoaderRoute: typeof SupportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/contact': {
      id: '/support/contact'
      path: '/support/contact'
      fullPath: '/support/contact'
      preLoaderRoute: typeof SupportContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/faq': {
      id: '/support/faq'
      path: '/support/faq'
      fullPath: '/support/faq'
      preLoaderRoute: typeof SupportFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/notices': {
      id: '/support/notices'
      path: '/support/notices'
      fullPath: '/support/notices'
      preLoaderRoute: typeof SupportNoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/$id': {
      id: '/admin/blog/$id'
      path: '/blog/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AdminBlogIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/new': {
      id: '/admin/blog/new'
      path: '/blog/new'
      fullPath: '/admin/blog/new'
      preLoaderRoute: typeof AdminBlogNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inquiries/': {
      id: '/admin/inquiries/'
      path: '/inquiries'
      fullPath: '/admin/inquiries/'
      preLoaderRoute: typeof AdminInquiriesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inquiries/$id': {
      id: '/admin/inquiries/$id'
      path: '/inquiries/$id'
      fullPath: '/admin/inquiries/$id'
      preLoaderRoute: typeof AdminInquiriesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notices/': {
      id: '/admin/notices/'
      path: '/notices'
      fullPath: '/admin/notices/'
      preLoaderRoute: typeof AdminNoticesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notices/$id': {
      id: '/admin/notices/$id'
      path: '/notices/$id'
      fullPath: '/admin/notices/$id'
      preLoaderRoute: typeof AdminNoticesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notices/new': {
      id: '/admin/notices/new'
      path: '/notices/new'
      fullPath: '/admin/notices/new'
      preLoaderRoute: typeof AdminNoticesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/portfolio/': {
      id: '/admin/portfolio/'
      path: '/portfolio'
      fullPath: '/admin/portfolio/'
      preLoaderRoute: typeof AdminPortfolioIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/portfolio/$id': {
      id: '/admin/portfolio/$id'
      path: '/portfolio/$id'
      fullPath: '/admin/portfolio/$id'
      preLoaderRoute: typeof AdminPortfolioIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/portfolio/new': {
      id: '/admin/portfolio/new'
      path: '/portfolio/new'
      fullPath: '/admin/portfolio/new'
      preLoaderRoute: typeof AdminPortfolioNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/press/': {
      id: '/admin/press/'
      path: '/press'
      fullPath: '/admin/press/'
      preLoaderRoute: typeof AdminPressIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/press/$id': {
      id: '/admin/press/$id'
      path: '/press/$id'
      fullPath: '/admin/press/$id'
      preLoaderRoute: typeof AdminPressIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/press/new': {
      id: '/admin/press/new'
      path: '/press/new'
      fullPath: '/admin/press/new'
      preLoaderRoute: typeof AdminPressNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/support/notices/': {
      id: '/support/notices/'
      path: '/'
      fullPath: '/support/notices/'
      preLoaderRoute: typeof SupportNoticesIndexRouteImport
      parentRoute: typeof SupportNoticesRoute
    }
    '/support/notices/$id': {
      id: '/support/notices/$id'
      path: '/$id'
      fullPath: '/support/notices/$id'
      preLoaderRoute: typeof SupportNoticesIdRouteImport
      parentRoute: typeof SupportNoticesRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBlogIdRoute: typeof AdminBlogIdRoute
  AdminBlogNewRoute: typeof AdminBlogNewRoute
  AdminInquiriesIdRoute: typeof AdminInquiriesIdRoute
  AdminNoticesIdRoute: typeof AdminNoticesIdRoute
  AdminNoticesNewRoute: typeof AdminNoticesNewRoute
  AdminPortfolioIdRoute: typeof AdminPortfolioIdRoute
  AdminPortfolioNewRoute: typeof AdminPortfolioNewRoute
  AdminPressIdRoute: typeof AdminPressIdRoute
  AdminPressNewRoute: typeof AdminPressNewRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
  AdminInquiriesIndexRoute: typeof AdminInquiriesIndexRoute
  AdminNoticesIndexRoute: typeof AdminNoticesIndexRoute
  AdminPortfolioIndexRoute: typeof AdminPortfolioIndexRoute
  AdminPressIndexRoute: typeof AdminPressIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminBlogIdRoute: AdminBlogIdRoute,
  AdminBlogNewRoute: AdminBlogNewRoute,
  AdminInquiriesIdRoute: AdminInquiriesIdRoute,
  AdminNoticesIdRoute: AdminNoticesIdRoute,
  AdminNoticesNewRoute: AdminNoticesNewRoute,
  AdminPortfolioIdRoute: AdminPortfolioIdRoute,
  AdminPortfolioNewRoute: AdminPortfolioNewRoute,
  AdminPressIdRoute: AdminPressIdRoute,
  AdminPressNewRoute: AdminPressNewRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
  AdminInquiriesIndexRoute: AdminInquiriesIndexRoute,
  AdminNoticesIndexRoute: AdminNoticesIndexRoute,
  AdminPortfolioIndexRoute: AdminPortfolioIndexRoute,
  AdminPressIndexRoute: AdminPressIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogIdRoute: typeof BlogIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogIdRoute: BlogIdRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface PortfolioRouteChildren {
  PortfolioIdRoute: typeof PortfolioIdRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioIdRoute: PortfolioIdRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

interface SupportNoticesRouteChildren {
  SupportNoticesIdRoute: typeof SupportNoticesIdRoute
  SupportNoticesIndexRoute: typeof SupportNoticesIndexRoute
}

const SupportNoticesRouteChildren: SupportNoticesRouteChildren = {
  SupportNoticesIdRoute: SupportNoticesIdRoute,
  SupportNoticesIndexRoute: SupportNoticesIndexRoute,
}

const SupportNoticesRouteWithChildren = SupportNoticesRoute._addFileChildren(
  SupportNoticesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  PortfolioRoute: PortfolioRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AboutHistoryRoute: AboutHistoryRoute,
  AboutLocationRoute: AboutLocationRoute,
  AboutPressRoute: AboutPressRoute,
  AboutVisionRoute: AboutVisionRoute,
  BusinessAiSolutionsRoute: BusinessAiSolutionsRoute,
  BusinessDataAnalysisRoute: BusinessDataAnalysisRoute,
  BusinessEducationRoute: BusinessEducationRoute,
  BusinessPlatformRoute: BusinessPlatformRoute,
  SupportContactRoute: SupportContactRoute,
  SupportFaqRoute: SupportFaqRoute,
  SupportNoticesRoute: SupportNoticesRouteWithChildren,
  AboutIndexRoute: AboutIndexRoute,
  BusinessIndexRoute: BusinessIndexRoute,
  SupportIndexRoute: SupportIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
